// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsP329Oh0iVUAHNF7uCB4z1z2AbkgWAQ',
    appId: '1:383974186515:web:ddf93e68b8c734beffe9e6',
    messagingSenderId: '383974186515',
    projectId: 'gastr0',
    authDomain: 'gastr0.firebaseapp.com',
    databaseURL: 'https://gastr0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gastr0.appspot.com',
    measurementId: 'G-GB5VHRHQ8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWxdAN4OLPax5D3LDLGtaF_r3EPCy0Ic',
    appId: '1:383974186515:android:7e05c5122a3f545fffe9e6',
    messagingSenderId: '383974186515',
    projectId: 'gastr0',
    databaseURL: 'https://gastr0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gastr0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuDBGv5MsWu-2n7yHjAbTubP_02w97e_Y',
    appId: '1:383974186515:ios:0cb9ca16bc78cf82ffe9e6',
    messagingSenderId: '383974186515',
    projectId: 'gastr0',
    databaseURL: 'https://gastr0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gastr0.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuDBGv5MsWu-2n7yHjAbTubP_02w97e_Y',
    appId: '1:383974186515:ios:0cb9ca16bc78cf82ffe9e6',
    messagingSenderId: '383974186515',
    projectId: 'gastr0',
    databaseURL: 'https://gastr0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gastr0.appspot.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcsP329Oh0iVUAHNF7uCB4z1z2AbkgWAQ',
    appId: '1:383974186515:web:8e99aa16fb428d99ffe9e6',
    messagingSenderId: '383974186515',
    projectId: 'gastr0',
    authDomain: 'gastr0.firebaseapp.com',
    databaseURL: 'https://gastr0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gastr0.appspot.com',
    measurementId: 'G-8B4S8Y6SR7',
  );
}
